[package]
name = "pong"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies.amethyst]
git = "https://github.com/amethyst/amethyst"
features = ["nightly"]

[dependencies]
log = "0.4.6"
serde = "1.0.90"